name = "beerlympiad"
main = "worker/index.ts"
compatibility_date = "2024-11-01"

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "beerlympiad"
database_id = "e373a4a1-8f88-45b5-bd82-4e96739c699a"
migrations_dir = "migrations"
